export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const FETCHING_GITHUB_USERS = "FETCHING_GITHUB_USERS";
export const FETCHED_GITHUB_USERS = "FETCHED_GITHUB_USERS";
export const FETCH_GITHUB_USERS_FAIL = "FETCH_GITHUB_USERS_FAIL";
